# sources:
# - https://hub.docker.com/r/bitnami/express/
# - https://raw.githubusercontent.com/bitnami/bitnami-docker-express/master/docker-compose.yml
version: '3'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  express:
    image: docker.io/bitnami/express:4
    ports:
      - '8085:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    # volumes:
    #   - './my-project:/app'
    depends_on:
      - mongodb
